/**
 * Stock Constants
 * @module @stock-assist/shared/constants/stocks
 */

/** Default watchlist - User's personal favorites */
export const DEFAULT_WATCHLIST: string[] = [
    'RELIANCE',
    'TCS',
    'INFY',
    'HDFCBANK',
    'ICICIBANK',
    'SBIN',
    'BHARTIARTL',
    'ITC',
    'KOTAKBANK',
    'LT',
];

/**
 * Nifty 100 Universe - Top 100 NSE stocks by market cap
 * Kept for backward compatibility
 */
export const NIFTY_100: string[] = [
    // === Nifty 50 ===
    'RELIANCE', 'TCS', 'HDFCBANK', 'INFY', 'ICICIBANK', 'BHARTIARTL',
    'SBIN', 'ITC', 'LT', 'KOTAKBANK', 'HINDUNILVR', 'AXISBANK',
    'BAJFINANCE', 'MARUTI', 'TITAN', 'SUNPHARMA', 'TATAMOTORS', 'HCLTECH',
    'WIPRO', 'ASIANPAINT', 'NTPC', 'ONGC', 'POWERGRID', 'M&M',
    'ADANIENT', 'ADANIPORTS', 'ULTRACEMCO', 'JSWSTEEL', 'TATASTEEL', 'BAJAJ-AUTO',
    'BAJAJFINSV', 'COALINDIA', 'NESTLEIND', 'TECHM', 'GRASIM', 'DRREDDY',
    'CIPLA', 'DIVISLAB', 'APOLLOHOSP', 'EICHERMOT', 'HEROMOTOCO', 'BPCL',
    'INDUSINDBK', 'HINDALCO', 'BRITANNIA', 'SBILIFE', 'HDFCLIFE', 'TATACONSUM',
    'SHRIRAMFIN', 'BEL',
    // === Nifty Next 50 ===
    'ADANIGREEN', 'AMBUJACEM', 'BANKBARODA', 'BERGEPAINT', 'BOSCHLTD', 'CANBK',
    'CHOLAFIN', 'COLPAL', 'DABUR', 'DLF', 'GAIL', 'GODREJCP',
    'HAVELLS', 'ICICIPRULI', 'IDEA', 'INDIGO', 'IOC', 'IRCTC',
    'JIOFIN', 'JSWENERGY', 'LICI', 'LTIM', 'LTTS', 'LUPIN',
    'MARICO', 'MAXHEALTH', 'MOTHERSON', 'NAUKRI', 'NHPC', 'OBEROIRLTY',
    'OFSS', 'PAGEIND', 'PERSISTENT', 'PIDILITIND', 'PNB', 'POLYCAB',
    'RECLTD', 'SBICARD', 'SIEMENS', 'SRF', 'TATAELXSI', 'TATAPOWER',
    'TORNTPHARM', 'TRENT', 'UNIONBANK', 'VEDL', 'VOLTAS', 'YESBANK',
    'ZOMATO', 'ZYDUSLIFE',
];

/**
 * Extended Screening Universe — ~200 liquid NSE stocks
 * Includes NIFTY 100 + Midcap 100 most liquid names.
 * The screener filters this down to the top 10 clearest setups.
 */
export const SCREENING_UNIVERSE: string[] = [
    ...NIFTY_100,

    // === Nifty Midcap 100 — Liquid midcaps ===
    'ABB', 'ABCAPITAL', 'ABFRL', 'ACC', 'ALKEM', 'ASHOKLEY',
    'ASTRAL', 'ATUL', 'AUBANK', 'AUROPHARMA', 'BALKRISIND', 'BANDHANBNK',
    'BATAINDIA', 'BHARATFORG', 'BIOCON', 'CANFINHOME', 'CHAMBLFERT', 'COFORGE',
    'CONCOR', 'COROMANDEL', 'CROMPTON', 'CUB', 'CUMMINSIND', 'DEEPAKNTR',
    'DELTACORP', 'DEVYANI', 'DIXON', 'ESCORTS', 'EXIDEIND', 'FEDERALBNK',
    'FORTIS', 'GLENMARK', 'GMRINFRA', 'GNFC', 'GODREJPROP', 'GRANULES',
    'GSPL', 'HAL', 'HINDPETRO', 'HONAUT', 'IDFCFIRSTB', 'IEX',
    'INDHOTEL', 'INDUSTOWER', 'IPCA', 'IRFC', 'JINDALSTEL', 'JUBLFOOD',
    'KALYANKJIL', 'KEI', 'LAURUSLABS', 'LICHSGFIN', 'LODHA', 'LTF',
    'MANAPPURAM', 'MFSL', 'MGL', 'MPHASIS', 'MRF', 'MUTHOOTFIN',
    'NAM-INDIA', 'NATIONALUM', 'NAVINFLUOR', 'NMDC', 'OBEROIRLTY', 'OIL',
    'PAYTM', 'PEL', 'PETRONET', 'PFC', 'PHOENIXLTD', 'PIIND',
    'POLICYBZR', 'PRESTIGE', 'PVRINOX', 'RAJESHEXPO', 'RAMCOCEM', 'RBLBANK',
    'SAIL', 'SOLARINDS', 'SONACOMS', 'STARHEALTH', 'SUNDARMFIN', 'SUNDRMFAST',
    'SUPREMEIND', 'SYNGENE', 'TATACHEM', 'TATACOMM', 'THERMAX', 'TIINDIA',
    'TIMKEN', 'TORNTPOWER', 'TVSMOTOR', 'UBL', 'UNITDSPR', 'UPL',
    'VIKAS', 'WHIRLPOOL', 'ZEEL',
];

/** Stock name mapping */
export const STOCK_NAMES: Record<string, string> = {
    // Nifty 50
    RELIANCE: 'Reliance Industries',
    TCS: 'Tata Consultancy Services',
    HDFCBANK: 'HDFC Bank',
    INFY: 'Infosys',
    ICICIBANK: 'ICICI Bank',
    BHARTIARTL: 'Bharti Airtel',
    SBIN: 'State Bank of India',
    ITC: 'ITC Limited',
    LT: 'Larsen & Toubro',
    KOTAKBANK: 'Kotak Mahindra Bank',
    HINDUNILVR: 'Hindustan Unilever',
    AXISBANK: 'Axis Bank',
    BAJFINANCE: 'Bajaj Finance',
    MARUTI: 'Maruti Suzuki',
    TITAN: 'Titan Company',
    SUNPHARMA: 'Sun Pharma',
    TATAMOTORS: 'Tata Motors',
    HCLTECH: 'HCL Technologies',
    WIPRO: 'Wipro',
    ASIANPAINT: 'Asian Paints',
    NTPC: 'NTPC Limited',
    ONGC: 'Oil & Natural Gas Corp',
    POWERGRID: 'Power Grid Corp',
    'M&M': 'Mahindra & Mahindra',
    ADANIENT: 'Adani Enterprises',
    ADANIPORTS: 'Adani Ports & SEZ',
    ULTRACEMCO: 'UltraTech Cement',
    JSWSTEEL: 'JSW Steel',
    TATASTEEL: 'Tata Steel',
    'BAJAJ-AUTO': 'Bajaj Auto',
    BAJAJFINSV: 'Bajaj Finserv',
    COALINDIA: 'Coal India',
    NESTLEIND: 'Nestle India',
    TECHM: 'Tech Mahindra',
    GRASIM: 'Grasim Industries',
    DRREDDY: "Dr. Reddy's Labs",
    CIPLA: 'Cipla',
    DIVISLAB: "Divi's Laboratories",
    APOLLOHOSP: 'Apollo Hospitals',
    EICHERMOT: 'Eicher Motors',
    HEROMOTOCO: 'Hero MotoCorp',
    BPCL: 'Bharat Petroleum',
    INDUSINDBK: 'IndusInd Bank',
    HINDALCO: 'Hindalco Industries',
    BRITANNIA: 'Britannia Industries',
    SBILIFE: 'SBI Life Insurance',
    HDFCLIFE: 'HDFC Life Insurance',
    TATACONSUM: 'Tata Consumer Products',
    SHRIRAMFIN: 'Shriram Finance',
    BEL: 'Bharat Electronics',

    // Nifty Next 50
    ADANIGREEN: 'Adani Green Energy',
    AMBUJACEM: 'Ambuja Cements',
    BANKBARODA: 'Bank of Baroda',
    BERGEPAINT: 'Berger Paints',
    BOSCHLTD: 'Bosch Limited',
    CANBK: 'Canara Bank',
    CHOLAFIN: 'Cholamandalam Inv & Fin',
    COLPAL: 'Colgate-Palmolive India',
    DABUR: 'Dabur India',
    DLF: 'DLF Limited',
    GAIL: 'GAIL India',
    GODREJCP: 'Godrej Consumer Products',
    HAVELLS: 'Havells India',
    ICICIPRULI: 'ICICI Prudential Life',
    IDEA: 'Vodafone Idea',
    INDIGO: 'InterGlobe Aviation',
    IOC: 'Indian Oil Corp',
    IRCTC: 'IRCTC',
    JIOFIN: 'Jio Financial Services',
    JSWENERGY: 'JSW Energy',
    LICI: 'Life Insurance Corp',
    LTIM: 'LTIMindtree',
    LTTS: 'L&T Technology Services',
    LUPIN: 'Lupin Limited',
    MARICO: 'Marico Limited',
    MAXHEALTH: 'Max Healthcare',
    MOTHERSON: 'Motherson Sumi Wiring',
    NAUKRI: 'Info Edge (Naukri)',
    NHPC: 'NHPC Limited',
    OBEROIRLTY: 'Oberoi Realty',
    OFSS: 'Oracle Financial Services',
    PAGEIND: 'Page Industries',
    PERSISTENT: 'Persistent Systems',
    PIDILITIND: 'Pidilite Industries',
    PNB: 'Punjab National Bank',
    POLYCAB: 'Polycab India',
    RECLTD: 'REC Limited',
    SBICARD: 'SBI Cards & Payment',
    SIEMENS: 'Siemens India',
    SRF: 'SRF Limited',
    TATAELXSI: 'Tata Elxsi',
    TATAPOWER: 'Tata Power',
    TORNTPHARM: 'Torrent Pharma',
    TRENT: 'Trent Limited',
    UNIONBANK: 'Union Bank of India',
    VEDL: 'Vedanta Limited',
    VOLTAS: 'Voltas Limited',
    YESBANK: 'Yes Bank',
    ZOMATO: 'Zomato Limited',
    ZYDUSLIFE: 'Zydus Lifesciences',

    // Midcap 100
    ABB: 'ABB India',
    ABCAPITAL: 'Aditya Birla Capital',
    ABFRL: 'Aditya Birla Fashion',
    ACC: 'ACC Limited',
    ALKEM: 'Alkem Laboratories',
    ASHOKLEY: 'Ashok Leyland',
    ASTRAL: 'Astral Limited',
    ATUL: 'Atul Limited',
    AUBANK: 'AU Small Finance Bank',
    AUROPHARMA: 'Aurobindo Pharma',
    BALKRISIND: 'Balkrishna Industries',
    BANDHANBNK: 'Bandhan Bank',
    BATAINDIA: 'Bata India',
    BHARATFORG: 'Bharat Forge',
    BIOCON: 'Biocon Limited',
    CANFINHOME: 'Can Fin Homes',
    CHAMBLFERT: 'Chambal Fertilisers',
    COFORGE: 'Coforge Limited',
    CONCOR: 'Container Corp of India',
    COROMANDEL: 'Coromandel International',
    CROMPTON: 'Crompton Greaves',
    CUB: 'City Union Bank',
    CUMMINSIND: 'Cummins India',
    DEEPAKNTR: 'Deepak Nitrite',
    DELTACORP: 'Delta Corp',
    DEVYANI: 'Devyani International',
    DIXON: 'Dixon Technologies',
    ESCORTS: 'Escorts Kubota',
    EXIDEIND: 'Exide Industries',
    FEDERALBNK: 'Federal Bank',
    FORTIS: 'Fortis Healthcare',
    GLENMARK: 'Glenmark Pharma',
    GMRINFRA: 'GMR Airports Infra',
    GNFC: 'Gujarat Narmada Fertilizers',
    GODREJPROP: 'Godrej Properties',
    GRANULES: 'Granules India',
    GSPL: 'Gujarat State Petronet',
    HAL: 'Hindustan Aeronautics',
    HINDPETRO: 'Hindustan Petroleum',
    HONAUT: 'Honeywell Automation',
    IDFCFIRSTB: 'IDFC First Bank',
    IEX: 'Indian Energy Exchange',
    INDHOTEL: 'Indian Hotels Company',
    INDUSTOWER: 'Indus Towers',
    IPCA: 'IPCA Laboratories',
    IRFC: 'Indian Railway Finance',
    JINDALSTEL: 'Jindal Steel & Power',
    JUBLFOOD: 'Jubilant FoodWorks',
    KALYANKJIL: 'Kalyan Jewellers',
    KEI: 'KEI Industries',
    LAURUSLABS: 'Laurus Labs',
    LICHSGFIN: 'LIC Housing Finance',
    LODHA: 'Macrotech Developers',
    LTF: 'L&T Finance',
    MANAPPURAM: 'Manappuram Finance',
    MFSL: 'Max Financial Services',
    MGL: 'Mahanagar Gas',
    MPHASIS: 'Mphasis Limited',
    MRF: 'MRF Limited',
    MUTHOOTFIN: 'Muthoot Finance',
    'NAM-INDIA': 'Nippon Life AMC',
    NATIONALUM: 'National Aluminium',
    NAVINFLUOR: 'Navin Fluorine',
    NMDC: 'NMDC Limited',
    OIL: 'Oil India Limited',
    PAYTM: 'One97 Communications',
    PEL: 'Piramal Enterprises',
    PETRONET: 'Petronet LNG',
    PFC: 'Power Finance Corp',
    PHOENIXLTD: 'Phoenix Mills',
    PIIND: 'PI Industries',
    POLICYBZR: 'PB Fintech',
    PRESTIGE: 'Prestige Estates',
    PVRINOX: 'PVR INOX',
    RAJESHEXPO: 'Rajesh Exports',
    RAMCOCEM: 'Ramco Cements',
    RBLBANK: 'RBL Bank',
    SAIL: 'Steel Authority of India',
    SOLARINDS: 'Solar Industries',
    SONACOMS: 'Sona BLW Precision',
    STARHEALTH: 'Star Health Insurance',
    SUNDARMFIN: 'Sundaram Finance',
    SUNDRMFAST: 'Sundram Fasteners',
    SUPREMEIND: 'Supreme Industries',
    SYNGENE: 'Syngene International',
    TATACHEM: 'Tata Chemicals',
    TATACOMM: 'Tata Communications',
    THERMAX: 'Thermax Limited',
    TIINDIA: 'Tube Investments',
    TIMKEN: 'Timken India',
    TORNTPOWER: 'Torrent Power',
    TVSMOTOR: 'TVS Motor Company',
    UBL: 'United Breweries',
    UNITDSPR: 'United Spirits',
    UPL: 'UPL Limited',
    VIKAS: 'Vikas Lifecare',
    WHIRLPOOL: 'Whirlpool India',
    ZEEL: 'Zee Entertainment',
};
