/**
 * Stock Constants
 * @module @stock-assist/shared/constants/stocks
 */

/** Default watchlist - User's personal favorites */
export const DEFAULT_WATCHLIST: string[] = [
    'RELIANCE',
    'TCS',
    'INFY',
    'HDFCBANK',
    'ICICIBANK',
    'SBIN',
    'BHARTIARTL',
    'ITC',
    'KOTAKBANK',
    'LT',
];

/**
 * Nifty 100 Universe - Top 100 NSE stocks by market cap
 * Used for code-level screening to find top 10 high-clarity setups
 */
export const NIFTY_100: string[] = [
    // === Nifty 50 ===
    'RELIANCE',
    'TCS',
    'HDFCBANK',
    'INFY',
    'ICICIBANK',
    'BHARTIARTL',
    'SBIN',
    'ITC',
    'LT',
    'KOTAKBANK',
    'HINDUNILVR',
    'AXISBANK',
    'BAJFINANCE',
    'MARUTI',
    'TITAN',
    'SUNPHARMA',
    'TATAMOTORS',
    'HCLTECH',
    'WIPRO',
    'ASIANPAINT',
    'NTPC',
    'ONGC',
    'POWERGRID',
    'M&M',
    'ADANIENT',
    'ADANIPORTS',
    'ULTRACEMCO',
    'JSWSTEEL',
    'TATASTEEL',
    'BAJAJ-AUTO',
    'BAJAJFINSV',
    'COALINDIA',
    'NESTLEIND',
    'TECHM',
    'GRASIM',
    'DRREDDY',
    'CIPLA',
    'DIVISLAB',
    'APOLLOHOSP',
    'EICHERMOT',
    'HEROMOTOCO',
    'BPCL',
    'INDUSINDBK',
    'HINDALCO',
    'BRITANNIA',
    'SBILIFE',
    'HDFCLIFE',
    'TATACONSUM',
    'SHRIRAMFIN',
    'BEL',

    // === Nifty Next 50 ===
    'ADANIGREEN',
    'AMBUJACEM',
    'BANKBARODA',
    'BERGEPAINT',
    'BOSCHLTD',
    'CANBK',
    'CHOLAFIN',
    'COLPAL',
    'DABUR',
    'DLF',
    'GAIL',
    'GODREJCP',
    'HAVELLS',
    'ICICIPRULI',
    'IDEA',
    'INDIGO',
    'IOC',
    'IRCTC',
    'JIOFIN',
    'JSWENERGY',
    'LICI',
    'LTIM',
    'LTTS',
    'LUPIN',
    'MARICO',
    'MAXHEALTH',
    'MOTHERSON',
    'NAUKRI',
    'NHPC',
    'OBEROIRLTY',
    'OFSS',
    'PAGEIND',
    'PERSISTENT',
    'PIDILITIND',
    'PNB',
    'POLYCAB',
    'RECLTD',
    'SBICARD',
    'SIEMENS',
    'SRF',
    'TATAELXSI',
    'TATAPOWER',
    'TORNTPHARM',
    'TRENT',
    'UNIONBANK',
    'VEDL',
    'VOLTAS',
    'YESBANK',
    'ZOMATO',
    'ZYDUSLIFE',
];

/** Stock name mapping */
export const STOCK_NAMES: Record<string, string> = {
    // Nifty 50
    RELIANCE: 'Reliance Industries',
    TCS: 'Tata Consultancy Services',
    HDFCBANK: 'HDFC Bank',
    INFY: 'Infosys',
    ICICIBANK: 'ICICI Bank',
    BHARTIARTL: 'Bharti Airtel',
    SBIN: 'State Bank of India',
    ITC: 'ITC Limited',
    LT: 'Larsen & Toubro',
    KOTAKBANK: 'Kotak Mahindra Bank',
    HINDUNILVR: 'Hindustan Unilever',
    AXISBANK: 'Axis Bank',
    BAJFINANCE: 'Bajaj Finance',
    MARUTI: 'Maruti Suzuki',
    TITAN: 'Titan Company',
    SUNPHARMA: 'Sun Pharma',
    TATAMOTORS: 'Tata Motors',
    HCLTECH: 'HCL Technologies',
    WIPRO: 'Wipro',
    ASIANPAINT: 'Asian Paints',
    NTPC: 'NTPC Limited',
    ONGC: 'Oil & Natural Gas Corp',
    POWERGRID: 'Power Grid Corp',
    'M&M': 'Mahindra & Mahindra',
    ADANIENT: 'Adani Enterprises',
    ADANIPORTS: 'Adani Ports & SEZ',
    ULTRACEMCO: 'UltraTech Cement',
    JSWSTEEL: 'JSW Steel',
    TATASTEEL: 'Tata Steel',
    'BAJAJ-AUTO': 'Bajaj Auto',
    BAJAJFINSV: 'Bajaj Finserv',
    COALINDIA: 'Coal India',
    NESTLEIND: 'Nestle India',
    TECHM: 'Tech Mahindra',
    GRASIM: 'Grasim Industries',
    DRREDDY: "Dr. Reddy's Labs",
    CIPLA: 'Cipla',
    DIVISLAB: "Divi's Laboratories",
    APOLLOHOSP: 'Apollo Hospitals',
    EICHERMOT: 'Eicher Motors',
    HEROMOTOCO: 'Hero MotoCorp',
    BPCL: 'Bharat Petroleum',
    INDUSINDBK: 'IndusInd Bank',
    HINDALCO: 'Hindalco Industries',
    BRITANNIA: 'Britannia Industries',
    SBILIFE: 'SBI Life Insurance',
    HDFCLIFE: 'HDFC Life Insurance',
    TATACONSUM: 'Tata Consumer Products',
    SHRIRAMFIN: 'Shriram Finance',
    BEL: 'Bharat Electronics',

    // Nifty Next 50
    ADANIGREEN: 'Adani Green Energy',
    AMBUJACEM: 'Ambuja Cements',
    BANKBARODA: 'Bank of Baroda',
    BERGEPAINT: 'Berger Paints',
    BOSCHLTD: 'Bosch Limited',
    CANBK: 'Canara Bank',
    CHOLAFIN: 'Cholamandalam Inv & Fin',
    COLPAL: 'Colgate-Palmolive India',
    DABUR: 'Dabur India',
    DLF: 'DLF Limited',
    GAIL: 'GAIL India',
    GODREJCP: 'Godrej Consumer Products',
    HAVELLS: 'Havells India',
    ICICIPRULI: 'ICICI Prudential Life',
    IDEA: 'Vodafone Idea',
    INDIGO: 'InterGlobe Aviation',
    IOC: 'Indian Oil Corp',
    IRCTC: 'IRCTC',
    JIOFIN: 'Jio Financial Services',
    JSWENERGY: 'JSW Energy',
    LICI: 'Life Insurance Corp',
    LTIM: 'LTIMindtree',
    LTTS: 'L&T Technology Services',
    LUPIN: 'Lupin Limited',
    MARICO: 'Marico Limited',
    MAXHEALTH: 'Max Healthcare',
    MOTHERSON: 'Motherson Sumi Wiring',
    NAUKRI: 'Info Edge (Naukri)',
    NHPC: 'NHPC Limited',
    OBEROIRLTY: 'Oberoi Realty',
    OFSS: 'Oracle Financial Services',
    PAGEIND: 'Page Industries',
    PERSISTENT: 'Persistent Systems',
    PIDILITIND: 'Pidilite Industries',
    PNB: 'Punjab National Bank',
    POLYCAB: 'Polycab India',
    RECLTD: 'REC Limited',
    SBICARD: 'SBI Cards & Payment',
    SIEMENS: 'Siemens India',
    SRF: 'SRF Limited',
    TATAELXSI: 'Tata Elxsi',
    TATAPOWER: 'Tata Power',
    TORNTPHARM: 'Torrent Pharma',
    TRENT: 'Trent Limited',
    UNIONBANK: 'Union Bank of India',
    VEDL: 'Vedanta Limited',
    VOLTAS: 'Voltas Limited',
    YESBANK: 'Yes Bank',
    ZOMATO: 'Zomato Limited',
    ZYDUSLIFE: 'Zydus Lifesciences',
};
