export const TRADING = {
    CAPITAL: 15000,
    MAX_RISK: 500,
    MAX_POSITION_PERCENT: 40,
    DEFAULT_STOP_LOSS_PERCENT: 1.5,
    MAX_STOP_LOSS_PERCENT: 2,
    MIN_RISK_REWARD: 1.5,
    WIN_RATE_TARGET: 70,
} as const;
